# Run trivy scans on the trust package container images every night.
name: trust-package-security-scan
on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: read

jobs:
  trust-package-security-scan:
    runs-on: ubuntu-latest

    if: github.repository == 'cert-manager/trust-manager'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        # Adding `fetch-depth: 0` makes sure tags are also fetched. We need
        # the tags so `git describe` returns a valid version.
        # see https://github.com/actions/checkout/issues/701 for extra info about this option
        with: { fetch-depth: 0 }

      - run: make scan-debian-bookworm-trust-package
      - run: make scan-debian-bullseye-trust-package
